# Generated by Django 2.2 on 2019-08-05 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chit_chat', '0003_auto_20190805_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
